#!/bin/bash
#PBS -P ${PROJECT}
#PBS -q normal
#PBS -l walltime=10:00:00
#PBS -l mem=32G
#PBS -l jobfs=400GB
#PBS -l ncpus=8
#PBS -l storage=gdata/xe2
#PBS -l wd

set -euo pipefail # safe mode
set -x # logging

## set up
ASSEMBLY=
ASSEMBLY_DIR=
READS=
READS_DIR=

module load samtools/1.9

echo ---copy to---
cp ${ASSEMBLY_DIR}/${ASSEMBLY} ${PBS_JOBFS}
cp ${READS_DIR}/${READS} ${PBS_JOBFS}

echo ---minimap2---
minimap2 -t ${PBS_NCPUS} -ax map-ont ${PBS_JOBFS}/${ASSEMBLY} ${PBS_JOBFS}/${READS} > ${PBS_JOBFS}/mapped_reads.sam
samtools sort -T ${PBS_JOBFS}/sort_tmp -@ ${PBS_NCPUS} ${PBS_JOBFS}/mapped_reads.sam > ${PBS_JOBFS}/sorted_mapped_reads.bam
samtools index -@ ${PBS_NCPUS} ${PBS_JOBFS}/sorted_mapped_reads.bam

echo ---copy back---
cp ${PBS_JOBFS}/sorted_mapped_reads.* .
